development:
  adapter: postgresql
  encoding: unicode
  database: psyfin_development
  pool: 5
  username: $USER
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: psyfin_test
  pool: 5
  username: $USER
  password: